SET client_encoding = 'UTF8';

CREATE TABLE IF NOT EXISTS public.author (
    id_author integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    last_name varchar,
    date_of_birth date,
    email varchar,
    phone_number varchar,
    username varchar,
    password varchar
);

CREATE TABLE IF NOT EXISTS public.post (
    id_post integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar,
    image varchar,
    text text,
    id_author integer,
    engine varchar,
    hp integer,
    "weight-kg" integer,
    max_speed_kmh integer,
    CONSTRAINT fk_post_author FOREIGN KEY (id_author)
        REFERENCES public.author(id_author)
);

CREATE TABLE IF NOT EXISTS public.session (
    sid varchar PRIMARY KEY,
    sess json NOT NULL,
    expire timestamp(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS "IDX_session_expire"
ON public.session (expire);

INSERT INTO public.author VALUES
(1, 'Roberto', 'Castro', '2005-06-07', 'robertocastrogomez05@gmail.com', '7774933661', 'RobertoCastro', 'Biker123'),
(2, 'Wicho', 'Ponce', '2005-01-09', 'wichosebassalinasponce@gmail.com', '2443816398', 'TwinchoPonce', 'Cuchao456');

INSERT INTO public.post VALUES
(1, 'BMW S1000R', './src/assets/BMWS1000R.jpg', 'La BMW S1000R es una naked deportiva derivada de la S1000RR...', 1, '4 cilindros en línea, 999 cc', 165, 199, 250),
(2, 'Nissan GTR R34', './src/assets/GTR-R34.jpg', 'El Nissan GT-R R34 es uno de los mayores íconos...', 2, '6 cilindros en línea 2.6L biturbo RB26DETT', 276, 1560, 250),
(3, 'Kawasaki Ninja H2R', './src/assets/H2R.jpg', 'La Ninja H2R es una motocicleta diseñada exclusivamente para circuito...', 1, '4 cilindros en línea supercargado, 998 cc', 310, 216, 400),
(4, 'Dodge Hellcat', './src/assets/Hellcat.jpg', 'El Hellcat redefine el concepto de muscle car moderno...', 2, 'V8 6.2L HEMI supercargado', 707, 2000, 327),
(5, 'Suzuki GSX-R1000R', './src/assets/suzuki.jpg', 'La GSX-R1000R es la evolución más avanzada...', 1, '4 cilindros en línea, 999 cc', 199, 203, 299),
(6, 'Porsche 911', './src/assets/Porsche911.jpg', 'El Porsche 911 es uno de los deportivos más emblemáticos...', 2, '6 cilindros bóxer 3.0L biturbo', 379, 1500, 293),
(7, 'Yamaha R1', './src/assets/yamahar1.jpg', 'La Yamaha R1 revolucionó el segmento superbike...', 1, '4 cilindros en línea crossplane, 998 cc', 200, 201, 299),
(8, 'Toyota Supra', './src/assets/Supra.jpg', 'El Toyota Supra MK4 se convirtió en leyenda...', 2, '6 cilindros en línea 3.0L 2JZ-GTE biturbo', 276, 1560, 250),
(9, 'Ducati Panigale V4', './src/assets/DucatiV4.jpg', 'La Panigale V4 marcó una nueva era...', 1, 'V4 Desmosedici Stradale 1103 cc', 215, 198, 299),
(10, 'Subaru WRX STI', './src/assets/WRX-STI.jpg', 'El WRX STI es un ícono del rally mundial...', 2, '4 cilindros bóxer 2.5L turbo', 305, 1540, 255),
(11, 'Mazda RX7', './src/assets/Mazda-RX7.jpg', 'El Mazda RX-7 RZ 2000 es una edición especial...', 2, 'Rotativo Wankel 13B-REW biturbo, 1.3L', 276, 1280, 250),
(12, 'Suzuki Hayabusa', './src/assets/Suzuki-Hayabusa.jpg', 'La Suzuki Hayabusa es una de las motocicletas deportivas más icónicas...', 1, '4 cilindros en línea, 1340 cc', 190, 264, 299);

SELECT setval(pg_get_serial_sequence('public.author','id_author'), (SELECT MAX(id_author) FROM public.author));
SELECT setval(pg_get_serial_sequence('public.post','id_post'), (SELECT MAX(id_post) FROM public.post));